runtime: nodejs
env: flex
service: glod-www
manual_scaling:  
  instances: 1
env_variables:
  INSTANCE_CONNECTION_NAME: ghost-175523:us-central1:glod-oio
beta_settings:  
  cloud_sql_instances: ghost-175523:us-central1:glod-oio